version: '2'
services:
    njitsas-app:
        image: njitsas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://njitsas-postgresql:5432/njitsas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    njitsas-postgresql:
        extends:
            file: postgresql.yml
            service: njitsas-postgresql
