version: '2'
services:
    njitsas-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/njitsas/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=njitsas
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
